controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

georoots_register:
    path: /register
    controller: App\Controller\AuthController::register

georoots_login:
    path: /login
    controller: App\Controller\AuthController::login


